#!/usr/bin/env bash
# _automation/scaffold.sh — project boilerplate generator
# Called exclusively by the root Makefile:
#   bash _automation/scaffold.sh <project_name> <device> <package> <speed>
#
# NEVER invoke this script directly from a project Makefile.

set -euo pipefail

# ── Arguments ─────────────────────────────────────────────────────────────────
PROJECT="${1:-}"
ARCH="${2:-MachXO3D}"
DEVICE="${3:-LCMXO3D-9400HC}"
PACKAGE="${4:-CABGA256}"
PERF_GRADE="${5:-5}"
OC="${6:-Commercial}"

if [ -z "$PROJECT" ]; then
  echo "ERROR: project name argument is required." >&2
  echo "       Usage: make init PROJECT=<name>" >&2
  exit 1
fi

# ── Rule 1 — Validate project name ───────────────────────────────────────────
if ! echo "$PROJECT" | grep -qE '^[A-Za-z][A-Za-z0-9_]*$'; then
  echo "ERROR: Invalid project name: '$PROJECT'" >&2
  echo "       Name must start with a letter and contain only [A-Za-z0-9_]." >&2
  echo "       Spaces, hyphens, dots, and leading digits are forbidden." >&2
  exit 1
fi

# ── Locate repo root ──────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROJECT_DIR="$REPO_ROOT/$PROJECT"

# ── Rule 2 — Refuse to overwrite ─────────────────────────────────────────────
if [ -d "$PROJECT_DIR" ]; then
  echo "ERROR: Directory '$PROJECT' already exists. Refusing to overwrite." >&2
  exit 1
fi

# ── Derive lowercase name for file naming ─────────────────────────────────────
PROJECT_LOWER="$(echo "$PROJECT" | tr '[:upper:]' '[:lower:]')"

# ── Rule 3 — Create directory tree ───────────────────────────────────────────
mkdir -p \
  "$PROJECT_DIR/src" \
  "$PROJECT_DIR/tb" \
  "$PROJECT_DIR/syn/out" \
  "$PROJECT_DIR/syn/logs" \
  "$PROJECT_DIR/par/out" \
  "$PROJECT_DIR/par/logs" \
  "$PROJECT_DIR/pgrm/logs" \
  "$PROJECT_DIR/sim/out" \
  "$PROJECT_DIR/sim/logs"

# ── Rule 4 — Write boilerplate files ─────────────────────────────────────────

# project.meta (batch flow fields: ARCH, PERF_GRADE, OC)
cat > "$PROJECT_DIR/project.meta" <<EOF
ARCH=$ARCH
DEVICE=$DEVICE
PACKAGE=$PACKAGE
PERF_GRADE=$PERF_GRADE
OC=$OC
DIAMOND_MIN_VERSION=3.14
TOP_MODULE=${PROJECT_LOWER}_top
SIM_TOOL=questa
EOF

# src/sources.f — first entry is the skeleton RTL file so make syn is runnable immediately
cat > "$PROJECT_DIR/src/sources.f" <<EOF
# RTL source files — one path per line, relative to project root
# Example: src/${PROJECT_LOWER}_top.v
src/${PROJECT_LOWER}_top.v
EOF

# src/<project>_top.v  (skeleton RTL)
cat > "$PROJECT_DIR/src/${PROJECT_LOWER}_top.v" <<EOF
// ${PROJECT_LOWER}_top.v — top-level module skeleton
// Generated by: make init PROJECT=$PROJECT
// Fill in ports and logic before running make syn.

module ${PROJECT_LOWER}_top (
    input  wire clk,
    input  wire rst_n
    // TODO: add ports
);

    // TODO: add logic

endmodule
EOF

# tb/tb_files.f — first entry is the skeleton testbench so make sim is runnable immediately
cat > "$PROJECT_DIR/tb/tb_files.f" <<EOF
# Testbench files — one path per line, relative to project root
# Example: tb/${PROJECT_LOWER}_tb.sv
tb/${PROJECT_LOWER}_tb.sv
EOF

# tb/<project>_tb.sv  (skeleton testbench)
# The timescale directive uses a backtick which requires careful quoting.
cat > "$PROJECT_DIR/tb/${PROJECT_LOWER}_tb.sv" <<'SVEOF'
// __TB_PLACEHOLDER___tb.sv — Questa Sim testbench skeleton
`timescale 1ns/1ps
SVEOF
# Append the variable-substituted portion
cat >> "$PROJECT_DIR/tb/${PROJECT_LOWER}_tb.sv" <<EOF

module ${PROJECT_LOWER}_tb;

    logic clk   = 0;
    logic rst_n = 0;

    ${PROJECT_LOWER}_top dut (
        .clk   (clk),
        .rst_n (rst_n)
    );

    always #5 clk = ~clk;  // 100 MHz

    initial begin
        #20 rst_n = 1;
        // TODO: add stimulus
        #1000;
        \$display("SIM DONE");
        \$finish;
    end

endmodule
EOF

# Fix the placeholder comment in the first line of the testbench
sed -i "s|__TB_PLACEHOLDER__|${PROJECT_LOWER}|g" "$PROJECT_DIR/tb/${PROJECT_LOWER}_tb.sv"

# par/top.lpf  (skeleton pin constraints — placed in par/ since only used by map/par)
cat > "$PROJECT_DIR/par/top.lpf" <<EOF
# top.lpf — Lattice Diamond pin constraint file
# Reference: Lattice Diamond User Guide, Appendix A
#
# LOCATE COMP "<port_name>" SITE "<pin_name>" ;
# IOBUF PORT "<port_name>" IO_TYPE=LVCMOS33 ;
#
# TODO: add pin assignments for this board
EOF

# Makefile (project-level, thin include only)
cat > "$PROJECT_DIR/Makefile" <<EOF
# $PROJECT/Makefile
# Do not add build logic here. All logic lives in _automation/common.mk.
include \$(shell git rev-parse --show-toplevel)/_automation/common.mk
EOF

# .gitignore (project-level — batch flow version with pgrm artifacts)
cat > "$PROJECT_DIR/.gitignore" <<'EOF'
# Flow build artifacts — each flow owns its own out/ and logs/
syn/out/
syn/logs/
par/out/
par/logs/
pgrm/*.bit
pgrm/*.jed
pgrm/*.fea
pgrm/logs/
sim/out/
sim/logs/

# Diamond intermediate files
*.ngo
*.ngd
*.mrp
*.par
*.prf
*.rpt
*.srp
*.twr
*.twx
*_map.*
*_par.*
*.ncd
*.pcf
*.drc
*_impl*/
*.bsn

# Diamond project backup (batch flow doesn't create .ldf, but kept for reference)
*.ldf.bak

# Diamond work directories
diamond_work/

# Questa Sim artifacts
work/
*.wlf
transcript
vsim.wlf
modelsim.ini
questa.ini
*_fast.vcd
*.vcd
EOF

# ── Rule 5 — Print success summary ───────────────────────────────────────────
echo ""
echo "Created project: $PROJECT"
echo "  $PROJECT/project.meta"
echo "  $PROJECT/src/sources.f"
echo "  $PROJECT/src/${PROJECT_LOWER}_top.v"
echo "  $PROJECT/tb/tb_files.f"
echo "  $PROJECT/tb/${PROJECT_LOWER}_tb.sv"
echo "  $PROJECT/par/top.lpf          (pin constraints for map/par)"
echo "  $PROJECT/pgrm/               (batch bitgen directory)"
echo "  $PROJECT/Makefile"
echo "  $PROJECT/.gitignore"

if [ "$ARCH" = "MachXO3D_TBD" ] || [ "$DEVICE" = "LCMXO3D-9400HC_TBD" ]; then
  echo ""
  echo "WARNING: Fill in ARCH, DEVICE, PACKAGE, PERF_GRADE, OC in $PROJECT/project.meta before building."
fi

echo ""
echo "Next steps:"
echo "  1. Fill in $PROJECT/project.meta  (ARCH, DEVICE, PACKAGE, PERF_GRADE, OC)"
echo "  2. Fill in $PROJECT/par/top.lpf   (pin assignments)"
echo "  3. Add RTL to $PROJECT/src/       and list files in src/sources.f"
echo "  4. cd $PROJECT"
echo "  5. source ../_automation/env.sh"
echo "  6. make syn                       (runs synthesis batch tool)"
echo "  7. make par                       (runs map + par batch tools)"
echo "  8. make pgrm                      (generates bitstream + JEDEC)"
echo ""