// uart_top.v — top-level module skeleton
// Generated by: make init PROJECT=uart
// Fill in ports and logic before running make syn.

module uart_top (
    input  wire clk,
    input  wire rst_n
    
    // TODO: add ports
);

    // TODO: add logic

endmodule
