// uart_top.v — top-level module skeleton
// Generated by: make init PROJECT=uart
// Fill in ports and logic before running make syn.
`timescale 1ns/1ps

module uart_top (
    input wire clk,
    input wire [1:0] sw,
    output wire [6:0] seg,
    output wire dp,
    output wire [3:0] an,
    output wire [1:0] led,
    output wire RsTx,
    input wire RsRx,
    output wire debug
);

LED_Driver status_driver (.sw_connector(sw),
                        .led_connector(led));

Transmit_Tx Tx_Mod (.clk_c(clk),
                    .sw_c(sw),
                    .RsTx_c(RsTx));

Reciver_Rx Rx_Mod (
    .clk_c(clk),
    .Rx_c(RsRx),
    .sw_c(sw),
    .seg_c(seg),
    .dp_c(dp),
    .an_c(an)
);

    assign debug = RsTx;  // Placeholder for debug signal
endmodule
